[32mINFO    [0m juju.model:model.py:2097 Deploying local:jammy/postgresql-k8s-1
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [allocating] waiting: installing agent
  second-postgresql-k8s/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] waiting: awaiting for cluster to start
  second-postgresql-k8s/1 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  second-postgresql-k8s/1 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  second-postgresql-k8s/1 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  second-postgresql-k8s/1 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [idle] active: Primary
  second-postgresql-k8s/1 [executing] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] maintenance: reconfiguring cluster
  second-postgresql-k8s/1 [executing] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [executing] active: Primary
  second-postgresql-k8s/1 [idle] unknown: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [idle] active: Primary
  second-postgresql-k8s/1 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [idle] active: Primary
  second-postgresql-k8s/1 [idle] waiting: awaiting for member to start
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  second-postgresql-k8s/0 [idle] active: Primary
  second-postgresql-k8s/1 [idle] active: 
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.0.0.5:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.0.0.5:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.0.0.5:16443/api/v1/namespaces/test/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: GET https://10.0.0.5:16443/api/v1/namespaces/test/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.8    unsupported  02:17:10Z

App                    Version  Status  Scale  Charm                Channel  Rev  Address         Exposed  Message
postgresql-k8s         14.11    active      3  postgresql-k8s                  0  10.152.183.155  no       Primary
postgresql-test-app             active      1  postgresql-test-app  edge     145  10.152.183.149  no       received database credentials of the first database
second-postgresql-k8s  14.11    active      2  postgresql-k8s                  1  10.152.183.52   no       Primary

Unit                      Workload  Agent  Address       Ports  Message
postgresql-k8s/0          active    idle   10.1.236.139         Primary
postgresql-k8s/1          active    idle   10.1.236.140         
postgresql-k8s/2*         active    idle   10.1.236.143         
postgresql-test-app/0*    active    idle   10.1.236.142         received database credentials of the first database
second-postgresql-k8s/0*  active    idle   10.1.236.146         Primary
second-postgresql-k8s/1   active    idle   10.1.236.147         

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-postgresql-k8s-1: 02:03:12 ERROR unit.postgresql-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/model.py", line 3022, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-postgresql-k8s-1/secret-get', '--label', 'database-peers.postgresql-k8s.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 1691, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 352, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 851, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 941, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 731, in _on_postgresql_pebble_ready
    self.unit.set_workload_version(self._patroni.rock_postgresql_version)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 1216, in _patroni
    self.get_secret(APP_SCOPE, REWIND_PASSWORD_KEY),
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 267, in get_secret
    return self.peer_relation_data(scope).get_secret(peers.id, secret_key)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 519, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1872, in get_secret
    and field not in self.current_secret_fields
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1832, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2066, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 996, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 506, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2055, in _get_relation_secret
    return self.secrets.get(label, secret_uri, legacy_labels=self._previous_labels())
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 702, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 605, in meta
    self._secret_meta = self._model.get_secret(label=label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/model.py", line 280, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/model.py", line 3370, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/model.py", line 3024, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR permission denied

unit-postgresql-k8s-1: 02:03:12 ERROR juju.worker.uniter.operation hook "postgresql-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-1: 02:03:12 ERROR juju.worker.uniter pebble poll failed for container "postgresql": failed to send pebble-ready event: hook failed
unit-postgresql-k8s-2: 02:09:41 ERROR unit.postgresql-k8s/2.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...